exclude :test_crlf_line_endings,   'the whole test is unsupported'
exclude :test_comment_interleaved, 'the whole test is unsupported'
exclude :test_comment_single,      'the whole test is unsupported'
exclude :test_tokenize,            'the whole test is unsupported'
exclude :test_tokenize_recover,    'the whole test is unsupported'
