exclude :test_crlf_line_endings,         'the whole test is unsupported'
exclude :test_comment_interleaved,       'the whole test is unsupported'
exclude :test_comment_single,            'the whole test is unsupported'
exclude :test_tokenize,                  'the whole test is unsupported'
exclude :test_tokenize_recover,          'the whole test is unsupported'
exclude :test_bug_ascii_8bit_in_literal, 'the whole test is unsupported'

exclude :test_ruby_bug_11107, 'reason'
exclude :test_bug_heredoc_do, 'reason'
exclude :test_heredoc, 'reason'
exclude :test_dedenting_heredoc, 'reason'
